export const ACTIONS = {
    GET_USER_TIME_ZONES: 'GET_USER_TIME_ZONES',
    DELETE_USER_TIME_ZONE: 'DELETE_USER_TIME_ZONE',
    GET_TIME_ZONES: 'GET_TIME_ZONES',
    SET_SUGGESTIONS: 'SET_SUGGESTIONS',
    ADD_USER_TIME_ZONE: 'ADD_USER_TIME_ZONE',
}